//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunEasi.Translations {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RunEasi.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string PracticeDashboard {
            get {
                return ResourceManager.GetString("PracticeDashboard", resourceCulture);
            }
        }
        
        internal static string AddPatient {
            get {
                return ResourceManager.GetString("AddPatient", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string LasName {
            get {
                return ResourceManager.GetString("LasName", resourceCulture);
            }
        }
        
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string PatientsTracked {
            get {
                return ResourceManager.GetString("PatientsTracked", resourceCulture);
            }
        }
        
        internal static string ActiveSensors {
            get {
                return ResourceManager.GetString("ActiveSensors", resourceCulture);
            }
        }
        
        internal static string RuneasiSessions {
            get {
                return ResourceManager.GetString("RuneasiSessions", resourceCulture);
            }
        }
        
        internal static string ManageMySensors {
            get {
                return ResourceManager.GetString("ManageMySensors", resourceCulture);
            }
        }
        
        internal static string MyPatients {
            get {
                return ResourceManager.GetString("MyPatients", resourceCulture);
            }
        }
        
        internal static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        internal static string LastRecording {
            get {
                return ResourceManager.GetString("LastRecording", resourceCulture);
            }
        }
        
        internal static string InfoAndKnowledge {
            get {
                return ResourceManager.GetString("InfoAndKnowledge", resourceCulture);
            }
        }
        
        internal static string RuneasiConnected {
            get {
                return ResourceManager.GetString("RuneasiConnected", resourceCulture);
            }
        }
        
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        internal static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        internal static string PatientDashboard {
            get {
                return ResourceManager.GetString("PatientDashboard", resourceCulture);
            }
        }
        
        internal static string BiofeedbackRunningScreen {
            get {
                return ResourceManager.GetString("BiofeedbackRunningScreen", resourceCulture);
            }
        }
        
        internal static string BiofeedbackWalkingScreen {
            get {
                return ResourceManager.GetString("BiofeedbackWalkingScreen", resourceCulture);
            }
        }
        
        internal static string BiofeedbackMetricScreen {
            get {
                return ResourceManager.GetString("BiofeedbackMetricScreen", resourceCulture);
            }
        }
        
        internal static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        internal static string ImpactMagnitude {
            get {
                return ResourceManager.GetString("ImpactMagnitude", resourceCulture);
            }
        }
        
        internal static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        internal static string TotalImpact {
            get {
                return ResourceManager.GetString("TotalImpact", resourceCulture);
            }
        }
        
        internal static string ImpactAvg {
            get {
                return ResourceManager.GetString("ImpactAvg", resourceCulture);
            }
        }
        
        internal static string DailyCumulativeImpact {
            get {
                return ResourceManager.GetString("DailyCumulativeImpact", resourceCulture);
            }
        }
        
        internal static string MostRecentRecording {
            get {
                return ResourceManager.GetString("MostRecentRecording", resourceCulture);
            }
        }
        
        internal static string DynamicStability {
            get {
                return ResourceManager.GetString("DynamicStability", resourceCulture);
            }
        }
        
        internal static string ImpactDuration {
            get {
                return ResourceManager.GetString("ImpactDuration", resourceCulture);
            }
        }
        
        internal static string ImpactDurationAvg {
            get {
                return ResourceManager.GetString("ImpactDurationAvg", resourceCulture);
            }
        }
        
        internal static string GroundContact {
            get {
                return ResourceManager.GetString("GroundContact", resourceCulture);
            }
        }
        
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        internal static string Cadence {
            get {
                return ResourceManager.GetString("Cadence", resourceCulture);
            }
        }
        
        internal static string CadenceAvg {
            get {
                return ResourceManager.GetString("CadenceAvg", resourceCulture);
            }
        }
        
        internal static string CadenceAvg2Lines {
            get {
                return ResourceManager.GetString("CadenceAvg2Lines", resourceCulture);
            }
        }
        
        internal static string Biofeedback {
            get {
                return ResourceManager.GetString("Biofeedback", resourceCulture);
            }
        }
        
        internal static string RecordSession {
            get {
                return ResourceManager.GetString("RecordSession", resourceCulture);
            }
        }
        
        internal static string FilterByTag {
            get {
                return ResourceManager.GetString("FilterByTag", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string OngoingRecording {
            get {
                return ResourceManager.GetString("OngoingRecording", resourceCulture);
            }
        }
        
        internal static string SessionDetail {
            get {
                return ResourceManager.GetString("SessionDetail", resourceCulture);
            }
        }
        
        internal static string CompareSessions {
            get {
                return ResourceManager.GetString("CompareSessions", resourceCulture);
            }
        }
        
        internal static string SessionComparison {
            get {
                return ResourceManager.GetString("SessionComparison", resourceCulture);
            }
        }
        
        internal static string ViewTagsAndNotes {
            get {
                return ResourceManager.GetString("ViewTagsAndNotes", resourceCulture);
            }
        }
        
        internal static string NewRecording {
            get {
                return ResourceManager.GetString("NewRecording", resourceCulture);
            }
        }
        
        internal static string NewRecordingInfo {
            get {
                return ResourceManager.GetString("NewRecordingInfo", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string SaveSummaryEvery {
            get {
                return ResourceManager.GetString("SaveSummaryEvery", resourceCulture);
            }
        }
        
        internal static string DisplaySummaryEvery {
            get {
                return ResourceManager.GetString("DisplaySummaryEvery", resourceCulture);
            }
        }
        
        internal static string RecordingOn {
            get {
                return ResourceManager.GetString("RecordingOn", resourceCulture);
            }
        }
        
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        internal static string RecordingDeviceNotInRange {
            get {
                return ResourceManager.GetString("RecordingDeviceNotInRange", resourceCulture);
            }
        }
        
        internal static string SynchronizingWith {
            get {
                return ResourceManager.GetString("SynchronizingWith", resourceCulture);
            }
        }
        
        internal static string SynchronizingBiofeedbackInProgress {
            get {
                return ResourceManager.GetString("SynchronizingBiofeedbackInProgress", resourceCulture);
            }
        }
        
        internal static string SynchronizingBiofeedbackInProgressDetails {
            get {
                return ResourceManager.GetString("SynchronizingBiofeedbackInProgressDetails", resourceCulture);
            }
        }
        
        internal static string SynchronizingBiofeedbackInProgressDetails2 {
            get {
                return ResourceManager.GetString("SynchronizingBiofeedbackInProgressDetails2", resourceCulture);
            }
        }
        
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        internal static string RecordingInProgress {
            get {
                return ResourceManager.GetString("RecordingInProgress", resourceCulture);
            }
        }
        
        internal static string SynchronizationInProgress {
            get {
                return ResourceManager.GetString("SynchronizationInProgress", resourceCulture);
            }
        }
        
        internal static string TagsAndNotes {
            get {
                return ResourceManager.GetString("TagsAndNotes", resourceCulture);
            }
        }
        
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        internal static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        internal static string AddToNotes {
            get {
                return ResourceManager.GetString("AddToNotes", resourceCulture);
            }
        }
        
        internal static string TagsCatalog {
            get {
                return ResourceManager.GetString("TagsCatalog", resourceCulture);
            }
        }
        
        internal static string CreateTag {
            get {
                return ResourceManager.GetString("CreateTag", resourceCulture);
            }
        }
        
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        internal static string AddToCatalog {
            get {
                return ResourceManager.GetString("AddToCatalog", resourceCulture);
            }
        }
        
        internal static string LoginIncorrect {
            get {
                return ResourceManager.GetString("LoginIncorrect", resourceCulture);
            }
        }
        
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        internal static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        internal static string NotInRange {
            get {
                return ResourceManager.GetString("NotInRange", resourceCulture);
            }
        }
        
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        internal static string SensorNotConnected {
            get {
                return ResourceManager.GetString("SensorNotConnected", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string CancelRecordingInfo {
            get {
                return ResourceManager.GetString("CancelRecordingInfo", resourceCulture);
            }
        }
        
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        internal static string ContinueRecording {
            get {
                return ResourceManager.GetString("ContinueRecording", resourceCulture);
            }
        }
        
        internal static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        internal static string InfoAndKnowledgeTitle {
            get {
                return ResourceManager.GetString("InfoAndKnowledgeTitle", resourceCulture);
            }
        }
        
        internal static string ImpactAndMovementCompensationMetrics {
            get {
                return ResourceManager.GetString("ImpactAndMovementCompensationMetrics", resourceCulture);
            }
        }
        
        internal static string RelativeValues {
            get {
                return ResourceManager.GetString("RelativeValues", resourceCulture);
            }
        }
        
        internal static string AbsoluteValues {
            get {
                return ResourceManager.GetString("AbsoluteValues", resourceCulture);
            }
        }
        
        internal static string StartedRecordingActionInfo {
            get {
                return ResourceManager.GetString("StartedRecordingActionInfo", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        internal static string DynStability {
            get {
                return ResourceManager.GetString("DynStability", resourceCulture);
            }
        }
        
        internal static string DynStabilityAvg {
            get {
                return ResourceManager.GetString("DynStabilityAvg", resourceCulture);
            }
        }
        
        internal static string GndContact {
            get {
                return ResourceManager.GetString("GndContact", resourceCulture);
            }
        }
        
        internal static string GndContactAvg {
            get {
                return ResourceManager.GetString("GndContactAvg", resourceCulture);
            }
        }
        
        internal static string EditPatient {
            get {
                return ResourceManager.GetString("EditPatient", resourceCulture);
            }
        }
        
        internal static string InternetConnectioError {
            get {
                return ResourceManager.GetString("InternetConnectioError", resourceCulture);
            }
        }
        
        internal static string ContactSupportMessage {
            get {
                return ResourceManager.GetString("ContactSupportMessage", resourceCulture);
            }
        }
        
        internal static string FirstSyncError {
            get {
                return ResourceManager.GetString("FirstSyncError", resourceCulture);
            }
        }
        
        internal static string LastSyncError {
            get {
                return ResourceManager.GetString("LastSyncError", resourceCulture);
            }
        }
        
        internal static string SensorRemoveError {
            get {
                return ResourceManager.GetString("SensorRemoveError", resourceCulture);
            }
        }
        
        internal static string RemoveRecordingInformation {
            get {
                return ResourceManager.GetString("RemoveRecordingInformation", resourceCulture);
            }
        }
        
        internal static string RemovePatientInformation {
            get {
                return ResourceManager.GetString("RemovePatientInformation", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string ReleaseLicense {
            get {
                return ResourceManager.GetString("ReleaseLicense", resourceCulture);
            }
        }
        
        internal static string ClaimLicense {
            get {
                return ResourceManager.GetString("ClaimLicense", resourceCulture);
            }
        }
        
        internal static string EmptyTagNameError {
            get {
                return ResourceManager.GetString("EmptyTagNameError", resourceCulture);
            }
        }
        
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        internal static string RefreshScanning {
            get {
                return ResourceManager.GetString("RefreshScanning", resourceCulture);
            }
        }
        
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        internal static string CancelRecording {
            get {
                return ResourceManager.GetString("CancelRecording", resourceCulture);
            }
        }
        
        internal static string ContinueLastRecording {
            get {
                return ResourceManager.GetString("ContinueLastRecording", resourceCulture);
            }
        }
        
        internal static string ContinueLastRecordingSensorError {
            get {
                return ResourceManager.GetString("ContinueLastRecordingSensorError", resourceCulture);
            }
        }
        
        internal static string ContinueLastRecordingConectionError {
            get {
                return ResourceManager.GetString("ContinueLastRecordingConectionError", resourceCulture);
            }
        }
        
        internal static string NoFreeLicensesAvailable {
            get {
                return ResourceManager.GetString("NoFreeLicensesAvailable", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string NoLicenseWarning {
            get {
                return ResourceManager.GetString("NoLicenseWarning", resourceCulture);
            }
        }
        
        internal static string NoLicenseInfo {
            get {
                return ResourceManager.GetString("NoLicenseInfo", resourceCulture);
            }
        }
        
        internal static string LocationInfo {
            get {
                return ResourceManager.GetString("LocationInfo", resourceCulture);
            }
        }
        
        internal static string CumulativeImpact {
            get {
                return ResourceManager.GetString("CumulativeImpact", resourceCulture);
            }
        }
        
        internal static string SensorConnectionError {
            get {
                return ResourceManager.GetString("SensorConnectionError", resourceCulture);
            }
        }
        
        internal static string SyncErrorTitle {
            get {
                return ResourceManager.GetString("SyncErrorTitle", resourceCulture);
            }
        }
        
        internal static string SyncErrorDescription {
            get {
                return ResourceManager.GetString("SyncErrorDescription", resourceCulture);
            }
        }
        
        internal static string UpdateFirmwareInfo {
            get {
                return ResourceManager.GetString("UpdateFirmwareInfo", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        internal static string ResumeUpdateFirmwareInfo {
            get {
                return ResourceManager.GetString("ResumeUpdateFirmwareInfo", resourceCulture);
            }
        }
        
        internal static string SeePlotSession {
            get {
                return ResourceManager.GetString("SeePlotSession", resourceCulture);
            }
        }
        
        internal static string SessionDetails {
            get {
                return ResourceManager.GetString("SessionDetails", resourceCulture);
            }
        }
        
        internal static string RelativeValue {
            get {
                return ResourceManager.GetString("RelativeValue", resourceCulture);
            }
        }
        
        internal static string ShowAbsoluteValue {
            get {
                return ResourceManager.GetString("ShowAbsoluteValue", resourceCulture);
            }
        }
        
        internal static string LeftPlotValue {
            get {
                return ResourceManager.GetString("LeftPlotValue", resourceCulture);
            }
        }
        
        internal static string RightPlotValue {
            get {
                return ResourceManager.GetString("RightPlotValue", resourceCulture);
            }
        }
        
        internal static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        internal static string Typical {
            get {
                return ResourceManager.GetString("Typical", resourceCulture);
            }
        }
        
        internal static string Elevated {
            get {
                return ResourceManager.GetString("Elevated", resourceCulture);
            }
        }
        
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        internal static string PlotLeftLegInfo {
            get {
                return ResourceManager.GetString("PlotLeftLegInfo", resourceCulture);
            }
        }
        
        internal static string PlotRightLegInfo {
            get {
                return ResourceManager.GetString("PlotRightLegInfo", resourceCulture);
            }
        }
        
        internal static string SoftwareVersionDownloadError {
            get {
                return ResourceManager.GetString("SoftwareVersionDownloadError", resourceCulture);
            }
        }
        
        internal static string SoftwareDownloadError {
            get {
                return ResourceManager.GetString("SoftwareDownloadError", resourceCulture);
            }
        }
        
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        internal static string PreviousUserSync {
            get {
                return ResourceManager.GetString("PreviousUserSync", resourceCulture);
            }
        }
        
        internal static string PreviousUserName {
            get {
                return ResourceManager.GetString("PreviousUserName", resourceCulture);
            }
        }
        
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        internal static string PreviousReports {
            get {
                return ResourceManager.GetString("PreviousReports", resourceCulture);
            }
        }
        
        internal static string NewReport {
            get {
                return ResourceManager.GetString("NewReport", resourceCulture);
            }
        }
        
        internal static string CustomReportName {
            get {
                return ResourceManager.GetString("CustomReportName", resourceCulture);
            }
        }
        
        internal static string RaportCreateInfo {
            get {
                return ResourceManager.GetString("RaportCreateInfo", resourceCulture);
            }
        }
        
        internal static string EmptyReportListTip {
            get {
                return ResourceManager.GetString("EmptyReportListTip", resourceCulture);
            }
        }
        
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        internal static string SelectSessionForReportInfo {
            get {
                return ResourceManager.GetString("SelectSessionForReportInfo", resourceCulture);
            }
        }
        
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        internal static string GenerateComparisonReport {
            get {
                return ResourceManager.GetString("GenerateComparisonReport", resourceCulture);
            }
        }
        
        internal static string GenerateSessionReport {
            get {
                return ResourceManager.GetString("GenerateSessionReport", resourceCulture);
            }
        }
        
        internal static string RemoveReportInfo {
            get {
                return ResourceManager.GetString("RemoveReportInfo", resourceCulture);
            }
        }
        
        internal static string ReportsNoInternetView {
            get {
                return ResourceManager.GetString("ReportsNoInternetView", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string PracticeProfile {
            get {
                return ResourceManager.GetString("PracticeProfile", resourceCulture);
            }
        }
        
        internal static string PracticeName {
            get {
                return ResourceManager.GetString("PracticeName", resourceCulture);
            }
        }
        
        internal static string PracticeLogo {
            get {
                return ResourceManager.GetString("PracticeLogo", resourceCulture);
            }
        }
        
        internal static string LoadFromGallery {
            get {
                return ResourceManager.GetString("LoadFromGallery", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        internal static string NoActiveLicense {
            get {
                return ResourceManager.GetString("NoActiveLicense", resourceCulture);
            }
        }
        
        internal static string ActiveLicense {
            get {
                return ResourceManager.GetString("ActiveLicense", resourceCulture);
            }
        }
        
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        internal static string LastSynchronizationDate {
            get {
                return ResourceManager.GetString("LastSynchronizationDate", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string SynchronizationPending {
            get {
                return ResourceManager.GetString("SynchronizationPending", resourceCulture);
            }
        }
        
        internal static string FullySync {
            get {
                return ResourceManager.GetString("FullySync", resourceCulture);
            }
        }
        
        internal static string SynchronizeNow {
            get {
                return ResourceManager.GetString("SynchronizeNow", resourceCulture);
            }
        }
        
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        internal static string TermsContidions {
            get {
                return ResourceManager.GetString("TermsContidions", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string NeverSynchronized {
            get {
                return ResourceManager.GetString("NeverSynchronized", resourceCulture);
            }
        }
        
        internal static string CropImageInformation {
            get {
                return ResourceManager.GetString("CropImageInformation", resourceCulture);
            }
        }
        
        internal static string SendDatabaseInfo {
            get {
                return ResourceManager.GetString("SendDatabaseInfo", resourceCulture);
            }
        }
        
        internal static string SendDatabaseSuccess {
            get {
                return ResourceManager.GetString("SendDatabaseSuccess", resourceCulture);
            }
        }
        
        internal static string OpenPDFError {
            get {
                return ResourceManager.GetString("OpenPDFError", resourceCulture);
            }
        }
        
        internal static string SavePDFError {
            get {
                return ResourceManager.GetString("SavePDFError", resourceCulture);
            }
        }
        
        internal static string OpenGalleryNoInternet {
            get {
                return ResourceManager.GetString("OpenGalleryNoInternet", resourceCulture);
            }
        }
        
        internal static string UpdateSensorInfoTitlePopup {
            get {
                return ResourceManager.GetString("UpdateSensorInfoTitlePopup", resourceCulture);
            }
        }
        
        internal static string UpdateSensorInfoPopup {
            get {
                return ResourceManager.GetString("UpdateSensorInfoPopup", resourceCulture);
            }
        }
        
        internal static string BiofeedbackIncorrectDataHint {
            get {
                return ResourceManager.GetString("BiofeedbackIncorrectDataHint", resourceCulture);
            }
        }
        
        internal static string BiofeedbackIncorrectDataHint2 {
            get {
                return ResourceManager.GetString("BiofeedbackIncorrectDataHint2", resourceCulture);
            }
        }
        
        internal static string BiofeedbackIncorrectDataHint3 {
            get {
                return ResourceManager.GetString("BiofeedbackIncorrectDataHint3", resourceCulture);
            }
        }
        
        internal static string BiofeedbackIncorrectDataHint4 {
            get {
                return ResourceManager.GetString("BiofeedbackIncorrectDataHint4", resourceCulture);
            }
        }
        
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        internal static string RebootError {
            get {
                return ResourceManager.GetString("RebootError", resourceCulture);
            }
        }
        
        internal static string RebootErrorTip {
            get {
                return ResourceManager.GetString("RebootErrorTip", resourceCulture);
            }
        }
        
        internal static string RebootSuccess {
            get {
                return ResourceManager.GetString("RebootSuccess", resourceCulture);
            }
        }
        
        internal static string RemoveTagInfo {
            get {
                return ResourceManager.GetString("RemoveTagInfo", resourceCulture);
            }
        }
        
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        internal static string Walk {
            get {
                return ResourceManager.GetString("Walk", resourceCulture);
            }
        }
        
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        internal static string Walking {
            get {
                return ResourceManager.GetString("Walking", resourceCulture);
            }
        }
        
        internal static string CamparissonTypeError {
            get {
                return ResourceManager.GetString("CamparissonTypeError", resourceCulture);
            }
        }
        
        internal static string FilterByType {
            get {
                return ResourceManager.GetString("FilterByType", resourceCulture);
            }
        }
        
        internal static string SelectionRecordingCountError {
            get {
                return ResourceManager.GetString("SelectionRecordingCountError", resourceCulture);
            }
        }
        
        internal static string NoPreviousReportsAvailable {
            get {
                return ResourceManager.GetString("NoPreviousReportsAvailable", resourceCulture);
            }
        }
        
        internal static string CreateReportInstruction {
            get {
                return ResourceManager.GetString("CreateReportInstruction", resourceCulture);
            }
        }
        
        internal static string RemoveNoteQuestion {
            get {
                return ResourceManager.GetString("RemoveNoteQuestion", resourceCulture);
            }
        }
        
        internal static string PlotUnavailable {
            get {
                return ResourceManager.GetString("PlotUnavailable", resourceCulture);
            }
        }
        
        internal static string CreateNewReport {
            get {
                return ResourceManager.GetString("CreateNewReport", resourceCulture);
            }
        }
        
        internal static string ReportGenerationFailed {
            get {
                return ResourceManager.GetString("ReportGenerationFailed", resourceCulture);
            }
        }
        
        internal static string Sensor404Error {
            get {
                return ResourceManager.GetString("Sensor404Error", resourceCulture);
            }
        }
        
        internal static string LearningCenter {
            get {
                return ResourceManager.GetString("LearningCenter", resourceCulture);
            }
        }
        
        internal static string GetFirmwareVersionError {
            get {
                return ResourceManager.GetString("GetFirmwareVersionError", resourceCulture);
            }
        }
        
        internal static string WalkingFeatureNeedUpdateSensor {
            get {
                return ResourceManager.GetString("WalkingFeatureNeedUpdateSensor", resourceCulture);
            }
        }
        
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string LowBatteryLevelInfo {
            get {
                return ResourceManager.GetString("LowBatteryLevelInfo", resourceCulture);
            }
        }
        
        internal static string OlderNews {
            get {
                return ResourceManager.GetString("OlderNews", resourceCulture);
            }
        }
        
        internal static string NewsHeader {
            get {
                return ResourceManager.GetString("NewsHeader", resourceCulture);
            }
        }
        
        internal static string StartRecordingError {
            get {
                return ResourceManager.GetString("StartRecordingError", resourceCulture);
            }
        }
        
        internal static string StartRecordingErrorPopupMessage {
            get {
                return ResourceManager.GetString("StartRecordingErrorPopupMessage", resourceCulture);
            }
        }
        
        internal static string RebootTip {
            get {
                return ResourceManager.GetString("RebootTip", resourceCulture);
            }
        }
        
        internal static string StopRecordingWithoutData {
            get {
                return ResourceManager.GetString("StopRecordingWithoutData", resourceCulture);
            }
        }
        
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        internal static string BluetootthDisableTip {
            get {
                return ResourceManager.GetString("BluetootthDisableTip", resourceCulture);
            }
        }
        
        internal static string StopRecordingErrorMessage {
            get {
                return ResourceManager.GetString("StopRecordingErrorMessage", resourceCulture);
            }
        }
        
        internal static string SyncInProgressHint {
            get {
                return ResourceManager.GetString("SyncInProgressHint", resourceCulture);
            }
        }
        
        internal static string NewAppVersionAvailableUpdate {
            get {
                return ResourceManager.GetString("NewAppVersionAvailableUpdate", resourceCulture);
            }
        }
        
        internal static string NewAppVersionAvailableForceUpdate {
            get {
                return ResourceManager.GetString("NewAppVersionAvailableForceUpdate", resourceCulture);
            }
        }
        
        internal static string StabilityMetrics {
            get {
                return ResourceManager.GetString("StabilityMetrics", resourceCulture);
            }
        }
        
        internal static string SpatioTemporalMetrics {
            get {
                return ResourceManager.GetString("SpatioTemporalMetrics", resourceCulture);
            }
        }
        
        internal static string OtherSummaryMetrics {
            get {
                return ResourceManager.GetString("OtherSummaryMetrics", resourceCulture);
            }
        }
        
        internal static string ImpactLoadingStats {
            get {
                return ResourceManager.GetString("ImpactLoadingStats", resourceCulture);
            }
        }
        
        internal static string BackToOverView {
            get {
                return ResourceManager.GetString("BackToOverView", resourceCulture);
            }
        }
        
        internal static string SessionRepot {
            get {
                return ResourceManager.GetString("SessionRepot", resourceCulture);
            }
        }
        
        internal static string SeeDetails {
            get {
                return ResourceManager.GetString("SeeDetails", resourceCulture);
            }
        }
        
        internal static string SeeRecommendations {
            get {
                return ResourceManager.GetString("SeeRecommendations", resourceCulture);
            }
        }
        
        internal static string RecommendationsImpactLoading {
            get {
                return ResourceManager.GetString("RecommendationsImpactLoading", resourceCulture);
            }
        }
        
        internal static string RecommendationsSymmetry {
            get {
                return ResourceManager.GetString("RecommendationsSymmetry", resourceCulture);
            }
        }
        
        internal static string RecommendationsDynamicStability {
            get {
                return ResourceManager.GetString("RecommendationsDynamicStability", resourceCulture);
            }
        }
        
        internal static string WeakestLink {
            get {
                return ResourceManager.GetString("WeakestLink", resourceCulture);
            }
        }
        
        internal static string Relevance {
            get {
                return ResourceManager.GetString("Relevance", resourceCulture);
            }
        }
        
        internal static string LinkedTo {
            get {
                return ResourceManager.GetString("LinkedTo", resourceCulture);
            }
        }
        
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        internal static string WeakestLinkIM {
            get {
                return ResourceManager.GetString("WeakestLinkIM", resourceCulture);
            }
        }
        
        internal static string WeakestLinkIML {
            get {
                return ResourceManager.GetString("WeakestLinkIML", resourceCulture);
            }
        }
        
        internal static string WeakestLinkIMR {
            get {
                return ResourceManager.GetString("WeakestLinkIMR", resourceCulture);
            }
        }
        
        internal static string WeakestLinkID {
            get {
                return ResourceManager.GetString("WeakestLinkID", resourceCulture);
            }
        }
        
        internal static string WeakestLinkIDL {
            get {
                return ResourceManager.GetString("WeakestLinkIDL", resourceCulture);
            }
        }
        
        internal static string WeakestLinkIDR {
            get {
                return ResourceManager.GetString("WeakestLinkIDR", resourceCulture);
            }
        }
        
        internal static string WeakestLinkDS {
            get {
                return ResourceManager.GetString("WeakestLinkDS", resourceCulture);
            }
        }
        
        internal static string WeakestLinkDSL {
            get {
                return ResourceManager.GetString("WeakestLinkDSL", resourceCulture);
            }
        }
        
        internal static string WeakestLinkDSR {
            get {
                return ResourceManager.GetString("WeakestLinkDSR", resourceCulture);
            }
        }
        
        internal static string RelevanceIM {
            get {
                return ResourceManager.GetString("RelevanceIM", resourceCulture);
            }
        }
        
        internal static string RelevanceIML {
            get {
                return ResourceManager.GetString("RelevanceIML", resourceCulture);
            }
        }
        
        internal static string RelevanceIMR {
            get {
                return ResourceManager.GetString("RelevanceIMR", resourceCulture);
            }
        }
        
        internal static string RelevanceID {
            get {
                return ResourceManager.GetString("RelevanceID", resourceCulture);
            }
        }
        
        internal static string RelevanceIDL {
            get {
                return ResourceManager.GetString("RelevanceIDL", resourceCulture);
            }
        }
        
        internal static string RelevanceIDR {
            get {
                return ResourceManager.GetString("RelevanceIDR", resourceCulture);
            }
        }
        
        internal static string RelevanceDS {
            get {
                return ResourceManager.GetString("RelevanceDS", resourceCulture);
            }
        }
        
        internal static string RelevanceDSL {
            get {
                return ResourceManager.GetString("RelevanceDSL", resourceCulture);
            }
        }
        
        internal static string RelevanceDSR {
            get {
                return ResourceManager.GetString("RelevanceDSR", resourceCulture);
            }
        }
        
        internal static string LinkedToIM {
            get {
                return ResourceManager.GetString("LinkedToIM", resourceCulture);
            }
        }
        
        internal static string LinkedToIML {
            get {
                return ResourceManager.GetString("LinkedToIML", resourceCulture);
            }
        }
        
        internal static string LinkedToIMR {
            get {
                return ResourceManager.GetString("LinkedToIMR", resourceCulture);
            }
        }
        
        internal static string LinkedToID {
            get {
                return ResourceManager.GetString("LinkedToID", resourceCulture);
            }
        }
        
        internal static string LinkedToIDL {
            get {
                return ResourceManager.GetString("LinkedToIDL", resourceCulture);
            }
        }
        
        internal static string LinkedToIDR {
            get {
                return ResourceManager.GetString("LinkedToIDR", resourceCulture);
            }
        }
        
        internal static string LinkedToDS {
            get {
                return ResourceManager.GetString("LinkedToDS", resourceCulture);
            }
        }
        
        internal static string LinkedToDSL {
            get {
                return ResourceManager.GetString("LinkedToDSL", resourceCulture);
            }
        }
        
        internal static string LinkedToDSR {
            get {
                return ResourceManager.GetString("LinkedToDSR", resourceCulture);
            }
        }
        
        internal static string TrainingIM {
            get {
                return ResourceManager.GetString("TrainingIM", resourceCulture);
            }
        }
        
        internal static string TrainingIML {
            get {
                return ResourceManager.GetString("TrainingIML", resourceCulture);
            }
        }
        
        internal static string TrainingIMR {
            get {
                return ResourceManager.GetString("TrainingIMR", resourceCulture);
            }
        }
        
        internal static string TrainingID {
            get {
                return ResourceManager.GetString("TrainingID", resourceCulture);
            }
        }
        
        internal static string TrainingIDL {
            get {
                return ResourceManager.GetString("TrainingIDL", resourceCulture);
            }
        }
        
        internal static string TrainingIDR {
            get {
                return ResourceManager.GetString("TrainingIDR", resourceCulture);
            }
        }
        
        internal static string TrainingDS {
            get {
                return ResourceManager.GetString("TrainingDS", resourceCulture);
            }
        }
        
        internal static string TrainingDSL {
            get {
                return ResourceManager.GetString("TrainingDSL", resourceCulture);
            }
        }
        
        internal static string TrainingDSR {
            get {
                return ResourceManager.GetString("TrainingDSR", resourceCulture);
            }
        }
        
        internal static string SessionOverViewTitle {
            get {
                return ResourceManager.GetString("SessionOverViewTitle", resourceCulture);
            }
        }
        
        internal static string NoQualityProfileAvailable {
            get {
                return ResourceManager.GetString("NoQualityProfileAvailable", resourceCulture);
            }
        }
        
        internal static string SeeRuneasiFramework {
            get {
                return ResourceManager.GetString("SeeRuneasiFramework", resourceCulture);
            }
        }
        
        internal static string TrainingTitle {
            get {
                return ResourceManager.GetString("TrainingTitle", resourceCulture);
            }
        }
        
        internal static string LocationSwitchedOffAndroid {
            get {
                return ResourceManager.GetString("LocationSwitchedOffAndroid", resourceCulture);
            }
        }
        
        internal static string FlightRatio {
            get {
                return ResourceManager.GetString("FlightRatio", resourceCulture);
            }
        }
        
        internal static string BiofeedbackVisualizationHint {
            get {
                return ResourceManager.GetString("BiofeedbackVisualizationHint", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        internal static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        internal static string LeftSymbol {
            get {
                return ResourceManager.GetString("LeftSymbol", resourceCulture);
            }
        }
        
        internal static string RightSymbol {
            get {
                return ResourceManager.GetString("RightSymbol", resourceCulture);
            }
        }
        
        internal static string SessionsNotExist {
            get {
                return ResourceManager.GetString("SessionsNotExist", resourceCulture);
            }
        }
        
        internal static string RunningQualityProgress {
            get {
                return ResourceManager.GetString("RunningQualityProgress", resourceCulture);
            }
        }
        
        internal static string WalkingCampare3Hint {
            get {
                return ResourceManager.GetString("WalkingCampare3Hint", resourceCulture);
            }
        }
    }
}
